export const GET_MUSIC_ALBUM_START = "GET_MUSIC_ALBUM_START";
export const GET_MUSIC_ALBUM_SUCCESS = "GET_MUSIC_ALBUM_SUCCESS";
export const GET_MUSIC_ALBUM_ERROR = "GET_MUSIC_ALBUM_ERROR";
export const GET_MUSIC_ALBUM_NO_DATA = "GET_MUSIC_ALBUM_NO_DATA";